workflows:
  - id: my-workflow
    start: say_hi
    tasks:
      say_hi:
        type: container
        next: say_next
        image: alpine
        with:
          baz: baz
        script: |
          #!/bin/sh
          apk add jq
          echo hi
          mv /runner/in.json /runner/out.json
      say_next:
        type: container
        next: say_bye
        image: alpine
        script: |
          #!/bin/sh
          echo next
          mv /runner/in.json /runner/out.json
      say_bye:
        type: container
        image: ubuntu
        env:
          foo: bar
        script: |
          #!/bin/sh
          echo bye
          mv /runner/in.json /runner/out.json
          env
