name: CLI

on:
  - push

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
          cache-dependency-path: ui/package-lock.json
      - run: cd ui && npm install
      - run: cd ui && npm run build
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

  package_cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS:
          - linux
          - darwin
        GOARCH:
          - arm64
          - amd64
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
          cache-dependency-path: ui/package-lock.json
      - uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - run: cd ui && npm install
      - run: cd ui && npm run build
      - name: Build
        run: go build -o build/crossjoin .
        env:
          CGO_ENABLED: "1"
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: crossjoin-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: build/crossjoin
