name: CLI

on:
  - push

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
          cache-dependency-path: ui/package-lock.json
      - run: cd ui && npm install
      - run: cd ui && npm run build
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

  package_cli:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            GOARCH: amd64
          - os: ubuntu-latest
            GOARCH: arm64
            CC: aarch64-linux-gnu-gcc
          - os: macos-latest
            GOARCH: amd64
    steps:
      - run: sudo apt update && sudo apt install gcc-aarch64-linux-gnu
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
          cache-dependency-path: ui/package-lock.json
      - run: cd ui && npm install
      - run: cd ui && npm run build
      - name: Build
        run: go build -o build/crossjoin .
        env:
          CGO_ENABLED: "1"
          GOARCH: ${{ matrix.GOARCH }}
          CC: ${{ matrix.CC }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: crossjoin-${{ matrix.os }}-${{ matrix.GOARCH }}
          path: build/crossjoin
